DROP TABLE IF EXISTS `post`;
CREATE TABLE `post` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `slug` VARCHAR(50) NOT NULL UNIQUE,
  `html` TEXT NOT NULL,
  `meta` TEXT NOT NULL,
  `year` INTEGER NOT NULL,
  `month` INTEGER NOT NULL,
  `day` INTEGER NOT NULL
);

DROP TABLE IF EXISTS `tag`;
CREATE TABLE `tag` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `postId` INTEGER NOT NULL REFERENCES `post`(`id`),
  `tag` VARCHAR(255) NOT NULL
);
